### ISSUE TITLE
Debugger terminating when I include the mapreduce section into the app.yaml

### ISSUE THREAD

**Issue by debnathsinha** [GoogleCloudPlatform/appengine-mapreduce#28]
I'm trying to follow the example on http://sookocheff.com/posts/2014-04-22-app-engine-mapreduce-api-part-2-running-a-mapreduce-job-using-mapreduceyaml/

However, when I put :

```
includes:
- mapreduce/include.yaml

handlers:
- url: /_ah/pipeline.*
  script: mapreduce.lib.pipeline.handlers._APP
  login: admin
```

into my app.yaml, the debugger  (PyDev) silently terminates on ANY page request. Just running dev_appserver from command line works fine. Unfortunately this means I cannot debug the code in PyDev which I am used to. Since it fails silently, I do not know how to debug it further? When I remove these lines (both have to be removed), the debugger start working again. For installing it, I copied the python/src folder into my main project root dir. Any suggestions on what could be wrong/how I can investigate it further?
