### ISSUE TITLE
Python: Update Pipeline Images Path

### ISSUE THREAD

**Issue by someone1** [GoogleCloudPlatform/appengine-mapreduce#42]
The include.yaml still points to an internally packaged pipeline library for static images which is no longer valid:

```yaml
handlers:
- url: /mapreduce/pipeline/images
  static_dir: mapreduce/lib/pipeline/ui/images
```

switching to `/pipeline/ui/images` or `../pipeline/ui/images` does not seem to do the trick, maybe the pipeline library should be updated instead and use absolute URLs and not relative?
